name: Build Geode Mod

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: win

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/**/*.geode

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: mac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mac-Build
          path: build/**/*.geode
